class CreateAccount_locator:
    # MrTitle_id = 'id_gender1'
    firstName_id = 'customer_firstname'
    lastName_id = 'customer_lastname'
    password_id = 'passwd'
    days_id = 'days'
    months_id ='months'
    years_id = 'years'
    address_id = 'address1'
    city_id = 'city'
    state_id = 'id_state'
    postalCode_id ='postcode'
    # country_id = 'id_country'
    phone_id = 'phone_mobile'
    aliasAdress_id = 'alias'
    register_id = 'submitAccount'

